[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # These will be replaced with actual values when you configure Supabase
  # For now, the app will run in demo mode
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

# If you have your Supabase credentials, replace the empty values above with:
# VITE_SUPABASE_URL = "https://your-project-id.supabase.co"
# VITE_SUPABASE_ANON_KEY = "your-anon-key-here"